In [6]:
import numpy as np

## Part 1

In [7]:
reports = []

with open('input_test.txt') as file:
    reports.append(file.readlines())

reports = np.transpose(reports)

In [8]:
safe_count = 0

for report in reports[:]:
    report_int = np.fromstring(report[0].strip(), sep=' ', dtype=np.int32)
    trends = np.zeros(len(report_int) - 1, dtype=np.int32)
    for level in range(len(report_int) - 1):
        trends[level] = report_int[level+1] - report_int[level]
        
    # print(trends)
    
    if all(trends >= 1) and all(trends <= 3):
        # print('safe\n')
        safe_count += 1
    elif all(trends >= -3) and all(trends <= -1):
        # print('safe\n')
        safe_count += 1
    # else:
        # print('unsafe\n')

print(f'safe count: {safe_count}')

safe count: 2


take each line of the input file and create a column vector of strings corresponding to each line. then, for each row:
1. convert from string to np int array
2. calculate the difference between consecutive numbers
3. store all the differences in an array

to check if the report is safe:
- check if all trends 1<= and <=3
- or if all trends -3<= and <=-1

keep track of the total number of safe reports, and print

## Part 2

In [9]:
safe_count = 0

for report in reports[:]:
    report_int = np.fromstring(report[0].strip(), sep=' ', dtype=np.int32)
    trends = np.zeros(len(report_int) - 1, dtype=np.int32)
    for level in range(len(report_int) - 1):
        trends[level] = report_int[level+1] - report_int[level]
        
    print(trends)
    
    if all(trends >= 1) and all(trends <= 3):
        print('safe\n')
        safe_count += 1
    elif all(trends >= -3) and all(trends <= -1):
        print('safe\n')
        safe_count += 1
    else:
        print('unsafe\n')
        

print(f'safe count: {safe_count}')

[-1 -2 -2 -1]
safe

[1 5 1 1]
unsafe

[-2 -1 -4 -1]
unsafe

[ 2 -1  2  1]
unsafe

[-2 -2  0 -3]
unsafe

[2 3 1 2]
safe

safe count: 2
